### ISSUE TITLE
T7Q & T9C: Multi-channel monitoring & SetPlaylist cmd

### ISSUE THREAD

**Issue by karltrowbridge1** [wildxmxtt/spotbot2#11]
## Dynamic playlist and channel monitoring/settings
Description: Allow for users to configure listeners to multiple channels & using a command, e.g. `!setplaylist` or `!playlist`, set playlist to default, multiple, or all channels in server.
Priority Level: low
Type: Quality of Life & Command

### To-Do:
- [ ] Configure the architect of playlists to channels (potential example below)
- [ ] Modify `on_message` func
- [ ] New `!setplaylist` cmd
- [ ] If playlist is set to all channels, use `and` operator to ignore if statement

---
### Examples: 
```json
{
"PLAYLIST1":[1234,2345],
"PLAYLIST2":["all"],
"PLAYLIST3":[3456,4567],
"PLAYLIST4":[1111]
}
```
PLAYLIST1
`"https://open.spotify.com/playlist/7JBm75EUBjh5s9VT2WtDle?si=a0c6069b50a54304"`
Array of Integers
`[1184330616964124599,1184331038188130634]`

```python
if( ctx.channel.id in playlist['PLAYLIST1'] and not "all" in data['PLAYLIST1'] ):
  # if statement for what channels are in what playlist setting and/or all channels enables
```
