### ISSUE TITLE
T5C Spotify Waveform Code

### ISSUE THREAD

**Issue by EmanG7** [wildxmxtt/spotbot2#5]
## Generate Spotify code wave form
Description: Should create a code wave form via a discord command
Priority Level: 1
Type: Command

Official Wavecode creation link: https://www.spotifycodes.com/#create

The **_real magic_** link: https://scannables.scdn.co/uri/plain/png/00000/white/640/spotify:track:unique_code
- **png** is image type
- **00000** is the background color (hex of color)
- **white** is the bar color (name of color
- **640** is pixel size of image
- **spotify:track:unique_code** is the identification code of the song that can be found in the Spotify song share URI

### To-Do List:
- [x] Discord Command Function w/ parameters: Spotify song URI 
- [x] Parsing arg:str into an accept identifier for a parameter of the URL
- [x] Async HTTP request on "https://scannables.scdn.co/uri/..."
- [x] Parse HTTP response into bytes form and send data as image into channel
- [x] Error Handling

### Extra:
- [ ] Function parameters for background (color hex) and bar (color name) colors
- [ ] Function parameters to not add it to the playlist
- [ ] Post-mortem command ability (reply to song link and make code from that)
